USE [master]
GO

/****** Object:  Database [TerraEyesDWH]    Script Date: 20-05-2022 11:38:18 ******/
CREATE DATABASE [TerraEyesDWH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TerraEyesDWH', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TerraEyesDWH.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TerraEyesDWH_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TerraEyesDWH_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TerraEyesDWH].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TerraEyesDWH] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET ANSI_NULLS OFF
GO

ALTER DATABASE [TerraEyesDWH] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET ARITHABORT OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TerraEyesDWH] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TerraEyesDWH] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TerraEyesDWH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TerraEyesDWH] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET RECOVERY FULL 
GO

ALTER DATABASE [TerraEyesDWH] SET  MULTI_USER 
GO

ALTER DATABASE [TerraEyesDWH] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TerraEyesDWH] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TerraEyesDWH] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TerraEyesDWH] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TerraEyesDWH] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TerraEyesDWH] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TerraEyesDWH] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TerraEyesDWH] SET  READ_WRITE 
GO


USE [TerraEyesDWH]
GO
CREATE SCHEMA [stage]
GO


USE [TerraEyesDWH]
GO
CREATE SCHEMA [edw]
GO